---
all:
  children:
    ubuntu_servers:
      hosts:
        talos-mgr2:
          ansible_host: "{{ talos_mgr2_ip }}"
        k8s-nfs:
          ansible_host: "{{ k8s_nfs_ip }}"
        vpn-vm:
          ansible_host: "{{ vpn_vm_ip }}"
          ansible_become_exe: sudo.ws
        apache-lxc:
          ansible_host: "{{ apache_lxc_ip }}"
          ansible_user: "{{ secondary_user }}"
        docker-prod:
          ansible_host: "{{ docker_prod_ip }}"
        docker-sand:
          ansible_host: "{{ docker_sand_ip }}"
        docker-test:
          ansible_host: "{{ docker_test_ip }}"
        docker-blue:
          ansible_host: "{{ docker_blue_ip }}"
        arr-vm:
          ansible_host: "{{ arr_ip }}"
        hjs-beta:
          ansible_host: "{{ hjs_beta_ip }}"
        vpn-lxc:
          ansible_host: "{{ vpn_lxc_ip }}"
          ansible_user: "{{ secondary_user }}"
        woodmaster:
          ansible_host: "{{ woodmaster_ip }}"
        talos-mgr:
          ansible_host: "{{ talos_mgr_ip }}"
        debian-gui:
          ansible_host: "{{ debian_gui_ip }}"
        # ubuntu-desktop:
          # ansible_host: "{{ ubuntu_desktop_ip }}"
          # ansible_become_exe: sudo.ws
        typescript-sand:
          ansible_host: "{{ typescript_sand_ip }}"
          ansible_become_exe: sudo.ws

    vps_servers:
      hosts:
        hjs-aussies:
          ansible_host: "{{ hjs_aussies_ip }}"
        metrics:
          ansible_host: "{{ metrics_ip }}"
        webserver:
          ansible_host: "{{ webserver_ip }}"