---
- name: Gather OS information
  hosts: ubuntu_servers
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Gather facts
      ansible.builtin.setup:
      
    - name: Display OS information
      debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "OS: {{ ansible_facts['distribution'] }}"
          - "Version: {{ ansible_facts['distribution_version'] }}"
          - "Release: {{ ansible_facts['distribution_release'] }}"
          - "Kernel: {{ ansible_facts['kernel'] }}"
          - "Architecture: {{ ansible_facts['architecture'] }}"